### ISSUE TITLE
Capstone Project Submission

### ISSUE THREAD

**Issue by wasaif89** [wasaif89/BookShelf#7]

**Comment by azfay3** [comment]
## **Hello Wasaif,**

### Thank you for submitting your capstone project!

### **Congratulations!** you've covered ALL requirements!


| Requirement  | Complete | Note
| ------------- | ------------- | ------------- |
| iOS application from scratch  | Done | Fulfilled |
| MVC design pattern | Partial  | Data modelling could be better |
| Support dark/light modes | Done  | Fulfilled |
| UIKit Framework | Done | Fulfilled |
| TableView and/or Collection View | Done | Fulfilled |
| Tab bar or a Navigation bar | Done | Fulfilled | 
| Autolayout | Done | Fulfilled |
| Gesture recognizer | Done | Fulfilled |
| Connect to back-end | Done | Fulfilled |
| Full CRUD | Done | Fulfilled |
| At least 2 models (more if it makes sense) | Done | Fulfilled |
| Add authentication for Users | Done | Fulfilled |
| Craft a README.md | Done | Fulfilled |

------

Finalize your presentation slides, and Salim will review the coding standard, architecture, functionality, UI and Bonus.
